# Generated by Django 4.2.4 on 2023-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortFoli_app', '0002_remove_portfoli_address_portfoli_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoli',
            name='Article',
            field=models.TextField(default='my article'),
        ),
    ]
